export const superblockData = [
  {
    id: "s_inodes_count",
    offset: 0,
    size: 4,
    description: "s_inodes_count",
  },
  {
    id: "s_blocks_count",
    offset: 4,
    size: 4,
    description: "s_blocks_count",
  },
  {
    id: "s_r_blocks_count",
    offset: 8,
    size: 4,
    description: "s_r_blocks_count",
  },
  {
    id: "s_free_blocks_count",
    offset: 12,
    size: 4,
    description: "s_free_blocks_count",
  },
  {
    id: "s_free_inodes_count",
    offset: 16,
    size: 4,
    description: "s_free_inodes_count",
  },
  {
    id: "s_first_data_block",
    offset: 20,
    size: 4,
    description: "s_first_data_block",
  },
  {
    id: "s_log_block_size",
    offset: 24,
    size: 4,
    description: "s_log_block_size",
  },
  {
    id: "s_log_frag_size",
    offset: 28,
    size: 4,
    description: "s_log_frag_size",
  },
  {
    id: "s_blocks_per_group",
    offset: 32,
    size: 4,
    description: "s_blocks_per_group",
  },
  {
    id: "s_frags_per_group",
    offset: 36,
    size: 4,
    description: "s_frags_per_group",
  },
  {
    id: "s_inodes_per_group",
    offset: 40,
    size: 4,
    description: "s_inodes_per_group",
  },
  {
    id: "s_mtime",
    offset: 44,
    size: 4,
    description: "s_mtime",
  },
  {
    id: "s_wtime",
    offset: 48,
    size: 4,
    description: "s_wtime",
  },
  {
    id: "s_mnt_count",
    offset: 52,
    size: 2,
    description: "s_mnt_count",
  },
  {
    id: "s_max_mnt_count",
    offset: 54,
    size: 2,
    description: "s_max_mnt_count",
  },
  {
    id: "s_magic",
    offset: 56,
    size: 2,
    description: "s_magic",
  },
  {
    id: "s_state",
    offset: 58,
    size: 2,
    description: "s_state",
  },
  {
    id: "s_errors",
    offset: 60,
    size: 2,
    description: "s_errors",
  },
  {
    id: "s_minor_rev_level",
    offset: 62,
    size: 2,
    description: "s_minor_rev_level",
  },
  {
    id: "s_lastcheck",
    offset: 64,
    size: 4,
    description: "s_lastcheck",
  },
  {
    id: "s_checkinterval",
    offset: 68,
    size: 4,
    description: "s_checkinterval",
  },
  {
    id: "s_creator_os",
    offset: 72,
    size: 4,
    description: "s_creator_os",
  },
  {
    id: "s_rev_level",
    offset: 76,
    size: 4,
    description: "s_rev_level",
  },
  {
    id: "s_def_resuid",
    offset: 80,
    size: 2,
    description: "s_def_resuid",
  },
  {
    id: "s_def_resgid",
    offset: 82,
    size: 2,
    description: "s_def_resgid",
  },
];

export const superblockExtendedData = [
  { id: "s_first_ino", offset: 84, size: 4, description: "s_first_ino" },
  { id: "s_inode_size", offset: 88, size: 2, description: "s_inode_size" },
  {
    id: "s_block_group_nr",
    offset: 90,
    size: 2,
    description: "s_block_group_nr",
  },
  {
    id: "s_feature_compat",
    offset: 92,
    size: 4,
    description: "s_feature_compat",
  },
  {
    id: "s_feature_incompat",
    offset: 96,
    size: 4,
    description: "s_feature_incompat",
  },
  {
    id: "s_feature_ro_compat",
    offset: 100,
    size: 4,
    description: "s_feature_ro_compat",
  },
  { id: "s_uuid", offset: 104, size: 16, description: "s_uuid" },
  { id: "s_volume_name", offset: 120, size: 16, description: "s_volume_name" },
  {
    id: "s_last_mounted",
    offset: 136,
    size: 64,
    description: "s_last_mounted",
  },
  { id: "s_algo_bitmap", offset: 200, size: 4, description: "s_algo_bitmap" },
  {
    id: "s_prealloc_blocks",
    offset: 204,
    size: 1,
    description: "s_prealloc_blocks",
  },
  {
    id: "s_prealloc_dir_blocks",
    offset: 205,
    size: 1,
    description: "s_prealloc_dir_blocks",
  },
  { id: "alignment", offset: "206", size: 2, description: "(alignment)" },
  {
    id: "s_journal_uuid",
    offset: 208,
    size: 16,
    description: "s_journal_uuid",
  },
  {
    id: "s_journal_inum",
    offset: 224,
    size: 16,
    description: "s_journal_inum",
  },
  { id: "s_journal_dev", offset: 228, size: 4, description: "s_journal_dev" },
  { id: "s_last_orphan", offset: 232, size: 4, description: "s_last_orphan" },
  { id: "s_hash_seed", offset: 236, size: 4, description: "s_hash_seed" },
  {
    id: "s_def_hash_version",
    offset: 252,
    size: 1,
    description: "s_def_hash_version",
  },
  {
    id: "padding",
    offset: 253,
    size: 3,
    description: "padding - reserved for future expansion",
  },
  {
    id: "s_default_mount_options",
    offset: 256,
    size: 4,
    description: "s_default_mount_options",
  },
  {
    id: "s_first_meta_bg",
    offset: 260,
    size: 4,
    description: "s_first_meta_bg",
  },
  {
    id: "unused",
    offset: 264,
    size: 760,
    description: "unused - reserved for future revisions",
  },
];
